version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'

  server:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    # volumes:
    #   - /app/node_modules
    #   - .:/app
    environment:
      - PORT=3004
    ports:
      - '3005:3004'