version: '3.9'
services:
  server:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - '3005:3005'
    environment:
      - PORT=3005
      - MONGO_DB_USERNAME=murmeltier
      - MONGO_BD_PASSWORD=4ixQiIg7p9B5fVGIrAvu